export const PROGRAMMES_BY_DEPARTMENT = {
  'Computer Science': ['B.Sc. Computer Science'],
  'Mathematics': ['B.Sc. Mathematics'],
  'Physics': ['B.Sc. Physics'],
  'Pure and Applied Chemistry': ['B.Sc. Chemistry'],
  'Environmental Science and Resource Management': ['B.Sc. Environmental Science and Resource Management'],
  'Accounting': ['B.Sc. Accounting'],
  'Business Administration': ['B.Sc. Business Administration'],
  'Entrepreneurial Studies': ['B.Sc. Entrepreneurial Studies'],
  'Public Administration': ['B.Sc. Public Administration'],
  'Procurement and Supply Chain Management': ['B.Sc. Procurement and Supply Chain Management'],
  'Economics': ['B.Sc. Economics'],
  'Mass Communication': ['B.Sc. Mass Communication'],
  'Political Science': ['B.Sc. Political Science'],
  'Criminology and Security Studies': ['B.Sc. Criminology and Security Studies'],
  'Peace Studies and Conflict Resolution': ['B.Sc. Peace Studies and Conflict Resolution'],
  'English Studies': ['B.A. English Studies'],
  'History and International Studies': ['B.A. History and International Studies'],
  'Christian Theology': ['B.A. Christian Theology'],
  'Islamic Studies': ['B.A. Islamic Studies'],
  'French': ['B.A. French'],
  'Educational Foundations': ['B.Sc.(Ed) Educational Foundations'],
  'Science Education': ['B.Sc.(Ed) Science Education'],
  'Languages Education': ['B.A.(Ed) Languages Education'],
  'Educational Management': ['B.Sc.(Ed) Educational Management'],
  'Public Health': ['B.Sc. Public Health'],
  'Nursing Science': ['B.NSc. Nursing Science'],
  'Environmental Health Science': ['B.Sc. Environmental Health Science'],
  'Common and Islamic Law': ['LL.B Law'],
  'Private and Property Law': ['LL.B Law'],
  'Public Law': ['LL.B Law'],
  'Agricultural Economics': ['B.Agric. Agricultural Economics'],
  'Animal Science': ['B.Agric. Animal Science'],
  'Crop Science': ['B.Agric. Crop Science'],
};

export function getProgrammesForDepartment(department) {
  return PROGRAMMES_BY_DEPARTMENT[department] || [];
}
